# Generated by Django 5.0.2 on 2024-04-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number_encrypted', models.TextField()),
                ('card_expiry', models.CharField(max_length=5)),
                ('user_id', models.IntegerField()),
                ('card_type', models.CharField(max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_name', models.CharField(max_length=100)),
                ('credit_apr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rewards', models.CharField(max_length=100)),
            ],
        ),
    ]
