# Generated by Django 5.0.2 on 2024-04-27 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_creditcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='card_expiry',
            new_name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='card_number_encrypted',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='credit_apr',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='rewards',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='user_id',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(default='0000 0000 0000 0000', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='cvv',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.creditcard')),
            ],
        ),
    ]
