# Generated by Django 5.0.2 on 2024-05-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_card_expiry_creditcard_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='card_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
